name: app-build-action-release
# 推送 Tag 时触发。
on:
  push:
    tags:
      - "v*"

jobs:
  # 打包 iOS
  build-ios:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      # 签出代码
      - uses: actions/checkout@v4
        with:
          ref: master

      # 设置 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # 打开 MAC Desktop 支持
      - name: Enable Flutter Desktop
        run: flutter config --enable-macos-desktop

      # 更新 Flutter 的 packages
      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      # 打包 iOS
      - name: Build IPA
        run: |
          cd simple_live_app
          flutter build ios --release --no-codesign

      # 创建未签名的 IPA
      - name: Create IPA
        run: |
          cd simple_live_app
          mkdir build/ios/iphoneos/Payload
          cp -R build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/Runner.app
          cd build/ios/iphoneos/
          zip -q -r ios_no_sign.ipa Payload
          cd ../../..

      # 上传 IPA 至 Artifacts
      - name: Upload IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: simple_live_app/build/ios/iphoneos/ios_no_sign.ipa

  # 打包 Windows
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # 签出代码
      - uses: actions/checkout@v4
        with:
          ref: master

      # 设置 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # 设置 Windows Desktop 支持
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop

      # 更新 Flutter 的 packages
      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get

      # 打包 Windows EXE
      - name: Build Windows EXE
        run: |
          cd simple_live_app
          flutter build windows --release

      # 检查 Windows EXE 是否成功生成
      - name: Check if Runner.exe exists
        run: |
          if [ -f "simple_live_app/build/windows/runner/Release/Runner.exe" ]; then
            echo "EXE file exists"
          else
            echo "EXE file not found"
          fi

      # 上传 Windows EXE 至 Artifacts
      - name: Upload Windows EXE to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: simple_live_app/build/windows/runner/Release/Runner.exe

      # 生成基于当前时间的版本号
      - name: Generate version number based on current time
        id: generate_version
        run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # 上传至 Release
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.generate_version.outputs.version }}"  # 自动生成版本号
          body: "Release based on current time"
          prerelease: false
          token: ${{ secrets.TOKEN }}
          files: |
            simple_live_app/build/ios/iphoneos/ios_no_sign.ipa
            simple_live_app/build/windows/runner/Release/Runner.exe

      # 完成
      - run: echo "🍏 This job's status is ${{ job.status }}."
